# AeroForge OS boot menu (Limine 9.x)
timeout: 0

/AeroForge OS
    protocol: limine
    path: boot():/boot/aerokernel
    module_path: boot():/boot/bin/aerosmss
    module_path: boot():/boot/bin/echod
    module_path: boot():/boot/bin/client
    module_path: boot():/boot/bin/crasher
    module_path: boot():/boot/bin/sectest
    module_path: boot():/boot/bin/nxtest
    module_path: boot():/boot/bin/rotest
    module_path: boot():/boot/bin/melody
    module_path: boot():/boot/bin/padtest
    module_path: boot():/boot/bin/savetest
    module_path: boot():/boot/bin/fputest
    module_path: boot():/boot/firmware/mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin
    module_path: boot():/boot/firmware/mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin
    module_path: boot():/boot/firmware/mediatek/BT_RAM_CODE_MT7922_1_1_hdr.bin
