# AeroForge OS boot menu (Limine 9.x)
timeout: 0

/AeroForge OS
    protocol: limine
    path: boot():/boot/aerokernel
    module_path: boot():/boot/bin/aerosmss
    module_path: boot():/boot/bin/echod
    module_path: boot():/boot/bin/client
    module_path: boot():/boot/bin/crasher
