[package]
name = "aerokernel"
version = "0.19.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "AeroKernel: the AeroForge OS kernel core"

[[bin]]
name = "aerokernel"
test = false
bench = false

[dependencies]
spin = "0.9"
font8x8 = { version = "0.3", default-features = false }
smoltcp = { version = "0.14", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "socket-icmp", "socket-dhcpv4", "socket-udp", "socket-tcp"] }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
debug = true
