[package]
name = "aero-userland"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "AeroForge OS user programs and libaero, their system call library"

[lib]
name = "aero"
path = "src/lib.rs"
test = false

[dependencies]
font8x8 = { version = "0.3", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
