[package]
name = "aero-userland"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "AeroForge OS user programs and libaero, their system call library"

[lib]
name = "aero"
path = "src/lib.rs"
test = false

[dependencies]
noto-sans-mono-bitmap = { version = "0.3", default-features = false, features = ["regular", "bold", "size_16", "size_32", "unicode-basic-latin", "unicode-latin-1-supplement", "size_20", "size_24"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
